
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.StudentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  course: 'course',
  status: 'status',
  lastLesson: 'lastLesson',
  progress: 'progress',
  loginId: 'loginId',
  password: 'password',
  level: 'level',
  target: 'target',
  phone: 'phone',
  joinDate: 'joinDate',
  totalLessons: 'totalLessons',
  internalNote: 'internalNote',
  toeicScore: 'toeicScore',
  cefr: 'cefr',
  vocabScore: 'vocabScore',
  grammarScore: 'grammarScore',
  listeningScore: 'listeningScore',
  speakingScore: 'speakingScore',
  goalTarget: 'goalTarget',
  goalProgress: 'goalProgress',
  biography: 'biography',
  occupation: 'occupation',
  avatarUrl: 'avatarUrl',
  coverUrl: 'coverUrl',
  questLevel: 'questLevel',
  questXP: 'questXP',
  questStreak: 'questStreak',
  lastQuestPlayedAt: 'lastQuestPlayedAt'
};

exports.Prisma.TeacherScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  status: 'status',
  role: 'role',
  bio: 'bio',
  joinDate: 'joinDate',
  rating: 'rating',
  loginId: 'loginId',
  password: 'password'
};

exports.Prisma.LessonScheduleScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  studentName: 'studentName',
  teacherName: 'teacherName',
  date: 'date',
  time: 'time',
  duration: 'duration',
  course: 'course',
  type: 'type',
  status: 'status',
  tags: 'tags',
  meetingPassword: 'meetingPassword',
  meetingUrl: 'meetingUrl'
};

exports.Prisma.LessonRecordScalarFieldEnum = {
  id: 'id',
  lessonId: 'lessonId',
  studentId: 'studentId',
  date: 'date',
  teacher: 'teacher',
  title: 'title',
  feedback: 'feedback',
  nextScope: 'nextScope',
  importantExpressions: 'importantExpressions',
  homework: 'homework',
  internalNote: 'internalNote',
  grammar: 'grammar',
  vocab: 'vocab',
  pronunciation: 'pronunciation',
  fluency: 'fluency'
};

exports.Prisma.TestScoreScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  type: 'type',
  testName: 'testName',
  date: 'date',
  grade: 'grade',
  score: 'score',
  totalScore: 'totalScore',
  trend: 'trend',
  createdAt: 'createdAt'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  teacherId: 'teacherId',
  sender: 'sender',
  text: 'text',
  time: 'time',
  read: 'read'
};

exports.Prisma.AnnouncementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  date: 'date',
  target: 'target',
  priority: 'priority'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  planName: 'planName',
  amount: 'amount',
  dueDate: 'dueDate',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.SchoolSettingsScalarFieldEnum = {
  id: 'id',
  schoolName: 'schoolName',
  timezone: 'timezone',
  defaultCourseDuration: 'defaultCourseDuration',
  allowStudentCancellation: 'allowStudentCancellation',
  cancellationDeadlineHours: 'cancellationDeadlineHours',
  monthlyGoal: 'monthlyGoal'
};

exports.Prisma.VocabProgressScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  level: 'level',
  stageIndex: 'stageIndex',
  completions: 'completions',
  perfectClears: 'perfectClears',
  highestScore: 'highestScore',
  mode: 'mode',
  lastPlayedAt: 'lastPlayedAt'
};

exports.Prisma.GrammarProgressScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  level: 'level',
  stageIndex: 'stageIndex',
  completions: 'completions',
  perfectClears: 'perfectClears',
  highestScore: 'highestScore',
  lastPlayedAt: 'lastPlayedAt'
};

exports.Prisma.DrillProgressScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  level: 'level',
  categoryId: 'categoryId',
  completions: 'completions',
  perfectClears: 'perfectClears',
  highestScore: 'highestScore',
  lastPlayedAt: 'lastPlayedAt'
};

exports.Prisma.GrammarPointScalarFieldEnum = {
  id: 'id',
  label: 'label',
  category: 'category',
  order: 'order'
};

exports.Prisma.GrammarMasteryScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  grammarPointId: 'grammarPointId',
  status: 'status',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  Student: 'Student',
  Teacher: 'Teacher',
  LessonSchedule: 'LessonSchedule',
  LessonRecord: 'LessonRecord',
  TestScore: 'TestScore',
  Message: 'Message',
  Announcement: 'Announcement',
  Invoice: 'Invoice',
  SchoolSettings: 'SchoolSettings',
  VocabProgress: 'VocabProgress',
  GrammarProgress: 'GrammarProgress',
  DrillProgress: 'DrillProgress',
  GrammarPoint: 'GrammarPoint',
  GrammarMastery: 'GrammarMastery'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
